server:
  port: 9090
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: frontEndService
          uri : lb://FRONT-END
          predicates:
            - Path=/board/**
          filters:
            - AddRequestHeader=first-request, first-requests-header1
            - AddResponseHeader=first-response, first-response-header1
        - id: clientService
          uri : lb://CLIENT
          predicates:
            - Path=/clientboard/**
          filters:
            - AddRequestHeader=second-request, second-requests-header2
            - AddResponseHeader=second-response, second-response-header2
        - id: frontEndAnotherService
          uri: lb://FRONT-END-ANOTHER
          predicates:
            - Path=/board/**

